name: feel_better
description: A Feel Better emotional support toolkit.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.7.0 <4.0.0"
  flutter: ">=3.29.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.5
  shared_preferences: ^2.5.3
  google_fonts: ^6.3.2
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4
  image: ^4.1.3

flutter:
  uses-material-design: true
  fonts:
    - family: Satoshi
      fonts:
        - asset: assets/fonts/Satoshi-Light.otf
          weight: 300
        - asset: assets/fonts/Satoshi-Regular.otf
          weight: 400
        - asset: assets/fonts/Satoshi-Medium.otf
          weight: 500
        - asset: assets/fonts/Satoshi-Bold.otf
          weight: 700
        - asset: assets/fonts/Satoshi-Black.otf
          weight: 900
  assets:
    - assets/icon/app_icon.png
    - content/emotions/
    - content/strategies/

flutter_icons:
  android: true
  ios: true
  web:
    generate: true
    image_path: assets/icon/app_icon.png
    favicon: true
  image_path: assets/icon/app_icon.png
  macos:
    generate: true
    image_path: assets/icon/app_icon.png
  windows:
    generate: true
    image_path: assets/icon/app_icon.png
  linux:
    generate: true
    image_path: assets/icon/app_icon.png
